In [1]:
import numpy as np

# Specify the path to your .npy file
file_path = 'resnext101-action-avgpool-300h/train.npy'

# Load the array from the .npy file
array = np.load(file_path)

# Now `array` contains the data from the .npy file
print(array)

[[0.11112656 0.07782514 0.8020758  ... 0.18528682 0.05740855 0.5908531 ]
 [0.11112656 0.07782514 0.8020758  ... 0.18528682 0.05740855 0.5908531 ]
 [0.11112656 0.07782514 0.8020758  ... 0.18528682 0.05740855 0.5908531 ]
 ...
 [0.5524929  0.03256309 0.39005145 ... 0.02646423 0.22285461 0.21512814]
 [0.5524929  0.03256309 0.39005145 ... 0.02646423 0.22285461 0.21512814]
 [0.5524929  0.03256309 0.39005145 ... 0.02646423 0.22285461 0.21512814]]
